sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sidnaik1975/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sidnaik1975/react-test npm test

after_success:
  - docker build -t sidnaik1975/multi-client ./client
  - docker build -t sidnaik1975/multi-nginx ./nginx
  - docker build -t sidnaik1975/multi-server ./server
  - docker build -t sidnaik1975/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to docker hub1
  - docker push sidnaik1975/multi-client
  - docker push sidnaik1975/multi-nginx
  - docker push sidnaik1975/multi-server
  - docker push sidnaik1975/multi-worker
